### PR TITLE
Milestone 6: Friendships v2

### PR DESCRIPTION
**Pull request by cliftondavies**
### Completed:
- [x] Gitflow
- [x] Github Actions
- [x] Rubocop
- [x] Stylelint
- [x] Implement friendships with 2 rows for mutual friendship
- [x] Unit and Integrations tests

### CODE REVIEW

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! 😄 Great work on your project everything looks very professional. However even if the code works it doesn't mean that its done in the right way, lets fix that!

## Changes Required 🔴 

- [ ] As Explained in this articles https://explainextended.com/2009/03/07/selecting-friends/ and https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table What should happen on your friendship model is that when friendship is confirmed, an additional row with reversed user-friend pair is created, This should happen on your friendship model (or friendRequest as you called it). 

- [ ] With the above solution you can implement something like this on your user model : 
`has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"`
`has_many :friends, through: :confirmed_friendships`

- [ ] All of this applies to pending request. Also right now your definitions for friend status is happening on your user controller, and it should be done like stated on point 1 of this review on your `Friendship` model.

- [ ] After making the changes remember to update `timeline_posts` to show the user post and all of the friends post (Confirmed friendship).

After making the requested changes please resubmit for another review.

Cheers! 👍

**Comment by cliftondavies** [comment]
Hi @MarioDena! :wave: 

I have implemented all requested changes. :memo:

Thanks for the review. :pray: :+1:

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Progress @cliftondavies :clap: However, some changes need to be applied in order to get approval for this milestone. Check :arrow_down: 

##### General (Required)
* [ ] Pull request should display passing code linter checks
* [ ] Add feature/integration tests (e.g, authentication, adding friends, commenting, etc.)

##### Implementation :warning: 
* [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
- Confirming friendship is supposed to happen at the friend_request model, not in controllers.
* [ ] in order to get all posts written by user on their friends, you can use simple method in User model (in order to NOT do it with Enumerables and at the controller level)

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by cliftondavies** [comment]
Hi @stratospherique! Thanks for the review. :+1: 

The following have now been implemented:

#### Friendship confirmation happens at the Friend_Request model.
#### An additional row is created with reversed user-friend pair on confirmation of friendship.
#### Retrieves all posts written by a user and their friends.
#### Additional integration tests for Adding friends, Posting, Commenting and Liking.

Happy coding! :man_technologist:

**Comment by Dandush03** [comment]
# Status: 🚀 Approved 🚀 

### Hey! Great job so far! 💪 
### Keep it up in your next project
# Happy Coding 🤓 💻

**Comment by cliftondavies** [comment]
Thanks, @Dandush03! 🙏 👍

**Pull request merged**
